;;; lf-emacs.el --- Little Fox Emacs
;;
;;; Commentary:
;;

;; Load org config
(let ((config-el (expand-file-name "lf-config.el" user-emacs-directory))
      (config-org (expand-file-name "lf-config.org" user-emacs-directory)))
  (if (and (file-exists-p config-el)
           (file-exists-p config-org)
           (time-less-p (file-attribute-modification-time (file-attributes config-org))
                        (file-attribute-modification-time (file-attributes config-el))))
      (load-file config-el)
    (if (file-exists-p config-org)
        (org-babel-load-file config-org)
      (error "No file `%s' found!! No configuration loaded!!" config-org))))

;; Auto-tangle lf-config.org on save
(defun lf/tangle-config-on-save ()
  "Tangle lf-config.org to lf-config.el when saved."
  (when (string-equal (buffer-file-name)
                      (expand-file-name "lf-config.org" user-emacs-directory))
    (let ((org-confirm-babel-evaluate nil))
      (org-babel-tangle))))

(add-hook 'after-save-hook #'lf/tangle-config-on-save)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(auto-save-file-name-transforms '((".*" "~/.emacs.d/auto-saves/" t)))
 '(backup-directory-alist '((".*" . "~/.emacs.d/backups/")))
 '(byte-compile-verbose nil)
 '(byte-compile-warnings '(cl-functions))
 '(column-number-mode t)
 '(comment-style 'multi-line)
 '(completion-styles '(orderless basic))
 '(default-frame-alist '((menu-bar-line) (fullscreen . maximized)))
 '(delete-selection-mode t)
 '(dired-dwim-target t)
 '(dired-listing-switches "-al --group-directories-first")
 '(dired-recursive-copies 'always)
 '(dired-recursive-deletes 'always)
 '(dired-use-ls-dired t)
 '(display-line-numbers 'visual)
 '(doom-modeline-mode t)
 '(eglot-ignored-server-capabilities '(:documentHighlightProvider :inlayHintProvider))
 '(emms-player-list '(emms-player-mpv))
 '(fill-column 80)
 '(global-auto-revert-mode t)
 '(global-diff-hl-mode t)
 '(indicate-empty-lines t)
 '(initial-buffer-choice t)
 '(initial-major-mode 'fundamental-mode)
 '(initial-scratch-message nil)
 '(lua-indent-level 2)
 '(marginalia-mode t)
 '(menu-bar-mode nil)
 '(org-hide-leading-stars t)
 '(package-selected-packages nil)
 '(prog-mode-hook
   '(subword-mode (lambda nil (when (mode-has-lsp-p) (eglot-ensure)))
		  electric-pair-local-mode))
 '(recentf-mode t)
 '(ring-bell-function 'ignore)
 '(save-place-mode t)
 '(savehist-mode t)
 '(scroll-bar-mode nil)
 '(scroll-conservatively 5)
 '(scroll-margin 5)
 '(scroll-step 1)
 '(sentence-end-double-space nil)
 '(size-indication-mode t)
 '(text-mode-hook '(text-mode-hook-identify toggle-word-wrap))
 '(tool-bar-mode nil)
 '(uniquify-buffer-name-style 'forward nil (uniquify))
 '(use-short-answers t)
 '(vertico-mode t)
 '(warning-suppress-log-types '((auto-save)))
 '(which-key-mode t)
 '(winner-mode t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(change-log-acknowledgment ((((class color) (min-colors 256)) :foreground "#b4befe")))
 '(change-log-date ((((class color) (min-colors 256)) :foreground "#a6e3a1")))
 '(change-log-name ((((class color) (min-colors 256)) :foreground "#fab387")))
 '(diff-context ((((class color) (min-colors 256)) :foreground "#89b4fa")))
 '(diff-file-header ((((class color) (min-colors 256)) :foreground "#f5c2e7")))
 '(diff-header ((((class color) (min-colors 256)) :foreground "#89b4fa")))
 '(diff-hunk-header ((((class color) (min-colors 256)) :foreground "#fab387")))
 '(gnus-button ((((class color) (min-colors 256)) :foreground "#8aadf4")))
 '(gnus-group-mail-3 ((((class color) (min-colors 256)) :foreground "#8aadf4")))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 256)) :foreground "#8aadf4")))
 '(gnus-header-content ((((class color) (min-colors 256)) :foreground "#7dc4e4")))
 '(gnus-header-from ((((class color) (min-colors 256)) :foreground "#cba6f7")))
 '(gnus-header-name ((((class color) (min-colors 256)) :foreground "#a6e3a1")))
 '(gnus-header-subject ((((class color) (min-colors 256)) :foreground "#8aadf4")))
 '(log-view-message ((((class color) (min-colors 256)) :foreground "#b4befe")))
 '(match ((((class color) (min-colors 256)) :background "#3e5768" :foreground "#cdd6f5")))
 '(modus-themes-search-current ((((class color) (min-colors 256)) :background "#f38ba8" :foreground "#11111b")) t)
 '(modus-themes-search-lazy ((((class color) (min-colors 256)) :background "#3e5768" :foreground "#cdd6f5")) t)
 '(newsticker-extra-face ((((class color) (min-colors 256)) :foreground "#9399b2" :height 0.8 :slant italic)))
 '(newsticker-feed-face ((((class color) (min-colors 256)) :foreground "#f38ba8" :height 1.2 :weight bold)))
 '(newsticker-treeview-face ((((class color) (min-colors 256)) :foreground "#cdd6f4")))
 '(newsticker-treeview-selection-face ((((class color) (min-colors 256)) :background "#3e5768" :foreground "#cdd6f5")))
 '(tab-bar ((((class color) (min-colors 256)) :background "#1e1e2e" :foreground "#bac2de")))
 '(tab-bar-tab ((((class color) (min-colors 256)) :background "#1e1e2e" :underline t)))
 '(tab-bar-tab-group-current ((((class color) (min-colors 256)) :background "#1e1e2e" :foreground "#bac2de" :underline t)))
 '(tab-bar-tab-group-inactive ((((class color) (min-colors 256)) :background "#1e1e2e" :foreground "#9399b2"))))
